### ISSUE TITLE
Error Refactoring

### ISSUE THREAD

**Issue by oldwomanjosiah** [cs361-spring2021-team4/TASched#45]
In order to make error state rendering more consistent across form views I am refactoring the following error types:

- `PageError`
- `LoginError`
- `UserEditError`
- `CourseError`
- `SectionError`
- `LabError`

To instead be one baseclass: `PageError[P]` which is generic over `P`. It can then be instantiated with a concrete `P` which is an enum containing the different places which an error could be attached on the page. E.g.

```python
class PageError(Generic[P]):

    def place(self) -> P:
        return self._place

class LoginPlace(Enum):
    USERNAME = 0

    def place_username(self) -> bool:
        return self is LoginPlace.USERNAME

LoginError = PageError[LoginPlace]

error: LoginError = # . . .
error.place().username()

# Or in the templates just error.place.username
```

## TODO

- [x] Update Error Classes
- [x] Update Error Construction
  - [x] User Create/Edit
  - [x] Course Create/Edit
  - [x] Section Create/Edit
  - [x] Lab Create/Edit
  - [x] Login
- [x] Update Error Usage in templates
  - [x] User Create/Edit
  - [x] Course Create/Edit
  - [x] Section Create/Edit
  - [x] Lab Create/Edit
  - [x] Login

**Comment by oldwomanjosiah** [comment]
We will also need to update many of the acceptance tests in order for this to be complete.
